name: Update File Workflow

on:
  repository_dispatch:
    types: [update_file]

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Get current branch
      id: vars
      run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

    - name: Update File Content
      env:
        FILE_PATH: ${{ github.event.client_payload.file_path }}
        FILE_CONTENT: ${{ toJson(github.event.client_payload.file_content) }}
      run: |
        echo '${{ env.FILE_CONTENT }}' > '${{ env.FILE_PATH }}'
        git config --global user.name "GitHub Actions"
        git config --global user.email "action@github.com"

    - name: Remove BOM from file name if present
      if: contains(env.FILE_PATH, '<0xfeff>')
      run: |
        original_file="$FILE_PATH"
        cleaned_file=$(echo "$original_file" | sed 's/<0xfeff>//')
        if [ "$original_file" != "$cleaned_file" ]; then
          mv "$original_file" "$cleaned_file"
          echo "File renamed from $original_file to $cleaned_file due to BOM removal."
          env:
            FILE_PATH: $cleaned_file
        fi

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Update ${{ env.FILE_PATH }} via GitHub Actions"
        git push origin ${{ steps.vars.outputs.branch }}
