name: Update File Workflow

on:
  repository_dispatch:
    types: [update_file]

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Get current branch
      id: vars
      run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

    - name: Update File Content
      env:
        FILE_PATH: ${{ github.event.client_payload.file_path }}
        FILE_CONTENT: ${{ toJson(github.event.client_payload.file_content) }}
      run: |
        echo '${{ env.FILE_CONTENT }}' > '${{ env.FILE_PATH }}'
        git config --global user.name "GitHub Actions"
        git config --global user.email "action@github.com"
