name: Update File Workflow

on:
  repository_dispatch:
    types: [update_file]

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Get current branch
      id: vars
      run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

    - name: Update File Content
      env:
        FILE_PATH: ${{ github.event.client_payload.file_path }}
        FILE_CONTENT: ${{ toJson(github.event.client_payload.file_content) }}
      run: |
        echo '${{ env.FILE_CONTENT }}' > '${{ env.FILE_PATH }}'
        git config --global user.name "GitHub Actions"
        git config --global user.email "action@github.com"
        git add .

    - name: Remove BOM from updated file
      if: contains(env.FILE_PATH, 'data') # 可选条件判断，确保只处理data目录下的文件
      run: |
        # 检查并移除指定文件的BOM
        if [[ $(file "$FILE_PATH") == *UTF-8* ]]; then
          echo "File is UTF-8 encoded, checking for BOM..."
          if head -c 3 "$FILE_PATH" | hexdump -C | grep -q '^00 00 fe'; then
            echo "BOM found, removing..."
            tail -c +4 "$FILE_PATH" > "${FILE_PATH}.tmp" && mv "${FILE_PATH}.tmp" "$FILE_PATH"
          fi
        else
          echo "File is not UTF-8 encoded, skipping BOM removal."
        fi

    - name: Commit and Push Changes
      run: |
        git commit -m "Update file and remove BOM via GitHub Actions"
        git push origin ${{ steps.vars.outputs.branch }}
